apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api-app
  labels:
    app: flask-api-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-api-app
  template:
    metadata:
      labels:
        app: flask-api-app
    spec:
      containers:
        - name: flask-api-app
          image: senthil123/pythonapiflask-app:latest
          ports:
            - containerPort: 5000  # Adjust based on your app's listening port         
---
apiVersion: v1
kind: Service
metadata:
  name: flask-api-app
spec:
  type: NodePort
  selector:
    app: flask-api-app
  ports:
    - port: 5000         # Port that the service will expose
      targetPort: 5000   # Port on the container
      nodePort: 30010    # NodePort (optional, Kubernetes will assign one if not specified)
